### ISSUE TITLE
Stops connecting

### ISSUE THREAD

**Issue by uamoreno** [marcelstoer/nodemcu-pyflasher#10]
Hello, im using a ESP8266 with an USB232 interface, at 9600bps:

Connecting....
Running Cesanta flasher stub...
Erasing flash (this may take a while)...
Erase took 2.4 seconds
Connecting...................

Lights onUSB232 stops blinking.
Bye

**Comment by marcelstoer** [comment]
This is an issue with either your driver or esptool.py itself.
