### ISSUE TITLE
what command is used to read chip id in esp8266

### ISSUE THREAD

**Issue by DJprasenjit** [marcelstoer/nodemcu-pyflasher#101]
i am using esp home flasher. when i flash a bin file there automatic read chip id and mac id. 
i wanted to khow the read chip id command used here/.
![image](https://github.com/marcelstoer/nodemcu-pyflasher/assets/108330279/475578d8-98fa-4e15-b7c6-fdc3b590659b)

**Comment by marcelstoer** [comment]
The output comes straight from esptool.py. This app only [invokes that tool](https://github.com/marcelstoer/nodemcu-pyflasher/blob/master/Main.py#L80-L106).
