### ISSUE TITLE
Display esptool.py command line

### ISSUE THREAD

**Issue by cverbiest** [marcelstoer/nodemcu-pyflasher#13]
Tried the tool (windows 10) and it worked perfectly. 
It would be nice if the command line used to start esptool.py would be displayed.

**Comment by marcelstoer** [comment]
Can you explain how/why this would help you?

**Comment by marcelstoer** [comment]
No feedback from OP -> closing

**Comment by oddstr13** [comment]
Would be handy for debugging, or just for learning how to do it from the commandline when that is needed.

**Comment by ThomDietrich** [comment]
I'd agree that this could be helpful because of the mentioned reasons.

**Comment by marcelstoer** [comment]
Will eventually be fixed with #43.
