### ISSUE TITLE
mac build problem and solution: can't not build with wxpython 4.0.*

### ISSUE THREAD

**Issue by KunFly** [marcelstoer/nodemcu-pyflasher#16]
on mac, try to build, but can't, some function miss like:SplashScreen, SPLASH_CENTRE_ON_SCREEN , SPLASH_TIMEOUT, wx.ST_SIZEGRIP. 

i fix this by modify the import path
from wx.adv import SplashScreen, SPLASH_CENTRE_ON_SCREEN , SPLASH_TIMEOUT
and
change wx.ST_SIZEGRIP to wx.STB_SIZEGRIP,

**Comment by marcelstoer** [comment]
I won't fix this until the project migrates to wxPython 4. That won't happen until a few months after wxPython 4 becomes officially available. [It's still in alpha](https://github.com/wxWidgets/Phoenix/releases) currently...
