### ISSUE TITLE
I compiled a version for my mac

### ISSUE THREAD

**Issue by detectingdragon** [marcelstoer/nodemcu-pyflasher#19]
My mac is running Mac OS X 10.9.5, if i share the application, can someone else use it? (On their own computer)

**Comment by marcelstoer** [comment]
How did you compile it? Feel free to attach/upload the binary to this "issue".

**Comment by detectingdragon** [comment]
I did the command ./build.sh

**Comment by detectingdragon** [comment]
Im uploading the result now.

**Comment by detectingdragon** [comment]
But it wont let me launch it: 
Traceback (most recent call last):
  File "nodemcu-pyflasher.py", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "Main.py", line 3, in <module>
    import aiohttp
ImportError: No module named 'wx'
Failed to execute script nodemcu-pyflasher
logout

**Comment by detectingdragon** [comment]
Here is the link: https://mega.nz/#F!bAQzXJYA!S04pmM2RN76Nmi7ygw3O8g

**Comment by marcelstoer** [comment]
If you want to build a binary you need to have wxPython and esptool (which brings pyserial) installed. See https://github.com/marcelstoer/nodemcu-pyflasher/issues/1#issuecomment-272253609 for details.
Also consider https://github.com/marcelstoer/nodemcu-pyflasher#status -> doesn't seem possible to have a working Mac binary.
