### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by lorenz24** [marcelstoer/nodemcu-pyflasher#25]
When I download the file "NodeMCU-PyFlasher-2.0.exe" from this link:
**https://github.com/marcelstoer/nodemcu-pyflasher/releases/download/v2.0/NodeMCU-PyFlasher-2.0.exe**
I get a Virus allert from my Windows defender.

**"Trojan:Win32/Azden.A!cl"**

Could you please double check about this problem.

Thanks Lorenz

**Comment by marcelstoer** [comment]
Good for you that you're taking this stuff serious. Virus detection engines work with probability and thus 100% certainty is hard to achieve. All major anti-virus engines consider this to be save: https://www.virustotal.com/#/file/a53b82454080bbedee88e9c0feb7a4b4e1edb3a9161736c8d1023cd8aac2c8eb
