### ISSUE TITLE
How to connect

### ISSUE THREAD

**Issue by elon-de-boer** [marcelstoer/nodemcu-pyflasher#26]
I've bought multiple NodeMCU's and the instalment of the first one went flawlessly, but when I tried to help a friend it wasn't able to detect a port with something attacted. I've tried it on multiple pc's but I could get it to work. Is there something I could do?

**Comment by marcelstoer** [comment]
That is something for a general ESP8266 forum such as http://www.esp8266.com/viewforum.php?f=6. I suspect you don't have the correct serial driver for the device/OS combination.
