### ISSUE TITLE
NodeMCU-PyFlasher-3.0 crashes on launch using macOS Sierra

### ISSUE THREAD

**Issue by phathak** [marcelstoer/nodemcu-pyflasher#31]
Hey,
mac user here using 10.12.5. I downloaded the latest releases today but I can't get to the GUI. It'll launch and then crash immediately. Have you seen this issue before?

Thank you.

**Comment by marcelstoer** [comment]
Just verified on my usually dormant Mac Mini that it crashes on macOS Sierra. No idea why, the failure isn't even reported in the sys log here.

**Comment by andrewoman** [comment]
10.12.6 as well. 
Service exited with abnormal code: 255

**Comment by marcelstoer** [comment]
Yep, I guess all pre-"High Sierra" versions are affected because I build on Sierra.

**Comment by MacGyverBeta** [comment]
Same here with 10.11.6. Console says:
"25.03.18 11:28:35,302 com.apple.xpc.launchd[1]: (com.frightanic.nodemcu-pyflasher.721632[3261]) Service exited with abnormal code: 255"

**Comment by JieGH** [comment]
the app may unable to run in my mac,system version 10.12.6

**Comment by masterkain** [comment]
```
[ruby-2.4.2] 22:30 ~ $ /Applications/NodeMCU-PyFlasher-3.0.app/Contents/MacOS/NodeMCU-PyFlasher
[1696] Error loading Python lib '/var/folders/4g/5_x3y4616cbbdysbv07hzf680000gn/T/_MEICDqR4S/Python': dlopen: dlopen(/var/folders/4g/5_x3y4616cbbdysbv07hzf680000gn/T/_MEICDqR4S/Python, 10): Symbol not found: _futimens
  Referenced from: /var/folders/4g/5_x3y4616cbbdysbv07hzf680000gn/T/_MEICDqR4S/Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/4g/5_x3y4616cbbdysbv07hzf680000gn/T/_MEICDqR4S/Python

```

**Comment by roboterm** [comment]
any fixes for this issue?
why has it been closed?

**Comment by marcelstoer** [comment]
Sierra is now two major OS versions behind. The next binary is likely going to be built on Mojave. If it happens to run on High Sierra, good, if not, too bad. I simply don't have the resources (neither macOS machines nor time) to build and test for OSs I don't personally use.
