### ISSUE TITLE
I stop working in linux

### ISSUE THREAD

**Issue by Kmiz07** [marcelstoer/nodemcu-pyflasher#33]
It worked very well but after upgrading my linux mint and python I could not make it work anymore. I suppose the problem is with versions of wxwindow and python, but I have not been able to solve it. So I will use esptool directly.
It hurts, because I liked a lot of pyflasher.

**Comment by marcelstoer** [comment]
As this is not an issue with PyFlasher but with your environment I'll close this. I'm quite convinced though that once you (re)install the required versions of all dependencies as per https://github.com/marcelstoer/nodemcu-pyflasher#build-it-yourself it'll run again.
