### ISSUE TITLE
.dmg does not open on Maverics 10.9.5

### ISSUE THREAD

**Issue by Shuurak** [marcelstoer/nodemcu-pyflasher#35]
![image](https://user-images.githubusercontent.com/26285937/39685248-dce4e864-51c9-11e8-92f3-b8a7e7b24c7f.png)
P.S. If it's an .app, is not it better to put it in a regular zip?
P.S.S. Forced to work for the Mavericks... what is there with compatibility?

**Comment by marcelstoer** [comment]
Sorry, the disk image is only for High Sierra. If you're stuck on older versions you need to install dependencies as per https://github.com/marcelstoer/nodemcu-pyflasher#build-it-yourself and then run `nodemcu-pyflasher.py` from the command line.
