### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by lucasromeiro** [marcelstoer/nodemcu-pyflasher#42]
Hello, I would like to know if there is any date expected to launch the program for MAC OS with the new changes. Thank you!!

**Comment by marcelstoer** [comment]
Sorry, not sure what you mean.

**Comment by lucasromeiro** [comment]
Thanks for the quick response!I have noticed that there have been some commits since the last version of the program for MAC OS (NodeMCU-PyFlasher-3.0.dmg) was released. I wonder if you are working on releasing something new. If there is any date in mind.

**Comment by marcelstoer** [comment]
Oh, got it. No fixed release date in mind. I'm actually waiting for new esptool.py release that could then integrate.

**Comment by lucasromeiro** [comment]
Thank you! I look forward.
Congratulations for your work.
Hugs!
