### ISSUE TITLE
Windows installers infected

### ISSUE THREAD

**Issue by spaceboy666** [marcelstoer/nodemcu-pyflasher#54]
virustotal reports that both Windows installers are infected.

**Comment by marcelstoer** [comment]
Not exactly...7 out of 67 tested engines report issues. Nothing I can do about that. I leave it up to you whether you trust those 7 more than the 60 others. You can always run Python directly if you install all the dependencies.

**Comment by marcelstoer** [comment]
Should be addressed in the newest release: https://frightanic.com/software-development/build-a-bootloader-for-pyinstaller/
