### ISSUE TITLE
Upgrade to esptool 2.8

### ISSUE THREAD

**Issue by marcelstoer** [marcelstoer/nodemcu-pyflasher#55]
https://github.com/espressif/esptool/releases/tag/v2.8

**Comment by utkarshsethi** [comment]
How may I contribute to this?

**Comment by jepoy11** [comment]
Hello, Where I can found the latest release for esptool 2.8?

**Comment by marcelstoer** [comment]
In master but not released yet https://github.com/marcelstoer/nodemcu-pyflasher/commit/d742c2ff136462c90e8c671673bc638c8d2a712f
