### ISSUE TITLE
Issue with ESP8285

### ISSUE THREAD

**Issue by underworldgamer** [marcelstoer/nodemcu-pyflasher#58]
Hello Marcel,

the program hangs on this position. Windows 10 x64 1903.
Newest Python installed.

https://imgur.com/a/VJOz3l5

BR
Mathias

**Comment by marcelstoer** [comment]
Sorry, nothing to do with this application. It's merely a GUI for esptool.py. If you were to install Python and run the script directly you would likely see the exact same behavior. Try playing with the baud rate and flash mode; maybe it helps.

**Comment by underworldgamer** [comment]
i have installed an old one of TTL USB converter and now it works :)
