### ISSUE TITLE
SecTaskLoadEntitlements Error 22

### ISSUE THREAD

**Issue by epollux** [marcelstoer/nodemcu-pyflasher#63]
I am getting SecTaskLoadEntitlements Error 22 when running the Mac App on OSX 10.11.6 (El Capitan). Is there a way around this? Thank you.

**Comment by marcelstoer** [comment]
Older macOS versions are not supported or tested. Binaries are built on Mojave and even that is a bit outdated.

You may be able to run it from the Python script if you clone this repository and then run `pip install -r requirements.txt` followed by `python nodemcu-pyflasher.py`.
