### ISSUE TITLE
won't compile on wxPython 4.1.0 use wxPython 4.0.7 instead

### ISSUE THREAD

**Issue by phenoptix** [marcelstoer/nodemcu-pyflasher#65]
Throws an error:

    serial_boxsizer.Add(reload_button, 0, wx.ALIGN_RIGHT, 20)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2098) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers

with the latest version of wxPython

Uninstalling with 
    pip uninstall wxpython
and reinstalling with
    pip install wxPython==4.0.7.post2

Gets it all working fine and dandy.

**Comment by marcelstoer** [comment]
The next version will use wxPython 4.1+.
