### ISSUE TITLE
no support for older mac os versions

### ISSUE THREAD

**Issue by ptaudio** [marcelstoer/nodemcu-pyflasher#68]
Like lots of people i have an older computer (macbook) in my garage to tinker with esp projects.
Unfortunately nodemcu pyflasher doesn't seem to support older versions like el capitan. As soon as i click the icon it highlights for second and then terminates again. Is there a possibility for older mac versions any time soon? Would be much appreciated :-)

**Comment by marcelstoer** [comment]
You need to build it yourself as per https://github.com/marcelstoer/nodemcu-pyflasher#build-it-yourself or at least install the Python dependencies and run it through Python.
