### ISSUE TITLE
Stuck at "connecting"

### ISSUE THREAD

**Issue by jaakattack** [marcelstoer/nodemcu-pyflasher#73]
Hi there! I successfully used the PyFlasher to flash my ESP8266 dev board two times. I need to flash it one more time, but this time, PyFlasher is stuck at "connecting..." no matter what cable or USB port I use. I redownloaded the PyFlasher and also reran the installation for the CP210x Universal Windows Driver. Any thoughts?

**Comment by marcelstoer** [comment]
As the PyFlasher is merely a GUI for https://github.com/espressif/esptool you would have to check with them, sorry.
