### ISSUE TITLE
Windows x64 executable flags a virus

### ISSUE THREAD

**Issue by dalbert2** [marcelstoer/nodemcu-pyflasher#75]
When you attempt to download the x64 executable download, VirusTotal detects it as containing a virus
![nodemcu_pyflasher_virus_warning](https://user-images.githubusercontent.com/5315514/108614667-7f399400-73ca-11eb-8e2e-c02f1a427a5b.jpg)
Malicious

**Comment by marcelstoer** [comment]
See #54

Each release has links to the virus report

<img width="629" alt="Screen Shot 2021-02-21 at 08 33 12" src="https://user-images.githubusercontent.com/624195/108618580-9d7daf00-741f-11eb-8a65-6d83a3d07b67.png">

**Comment by marcelstoer** [comment]
Should be addressed in the newest release: https://frightanic.com/software-development/build-a-bootloader-for-pyinstaller/
