### ISSUE TITLE
Warning: Image file at 0x0 doesn't look like an image file, so not changing any flash settings.

### ISSUE THREAD

**Issue by exrector** [marcelstoer/nodemcu-pyflasher#81]
Command: esptool.py --port /dev/cu.SLAB_USBtoUART --baud 115200 --after no_reset write_flash --flash_size detect --flash_mode dio 0x00000 /Users/exrector/Downloads/homekidd_blinds.bin --erase-all

esptool.py v3.0
Serial port /dev/cu.SLAB_USBtoUART
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: e8:db:84:a4:4b:a8
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Erasing flash (this may take a while)...
Chip erase completed successfully in 1.1s
**_Warning: Image file at 0x0 doesn't look like an image file, so not changing any flash settings._**
Wrote 472928 bytes (336752 compressed) at 0x00000000 in 30.0 seconds (effective 126.1 kbit/s)...
Hash of data verified.

Leaving...
Staying in bootloader.

Firmware successfully flashed. Unplug/replug or reset device 
to switch back to normal boot mode.

I know that this file BIN works 100 %
What happened?

**Comment by marcelstoer** [comment]
This tool expects single binaries that also have the bootloader and the partitions file packages into it (like from my cloud builder or the Docker image). See e.g. https://github.com/marcelstoer/docker-nodemcu-build/blob/master/build-esp32#L80 for details.
