### ISSUE TITLE
nodemcu-pyflasher on Windows 10 hangs

### ISSUE THREAD

**Issue by sysfrank** [marcelstoer/nodemcu-pyflasher#85]
When I run NodeMCU PyFlasher it hangs at the point where it says "Configuring Flash Size..." and gives no indication of an error
![Screenshot 2021-12-08 143610](https://user-images.githubusercontent.com/21147388/145272765-4a93d7c0-77fb-4a1b-8942-38681d6ecbea.jpg)
.

**Comment by marcelstoer** [comment]
As the PyFlasher is just a GUI around the esptool.py I suggest you try with their community at https://github.com/espressif/esptool. I suspect it's the specific combination of OS (version), driver (version) and the serial-to-USB chip.
