### ISSUE TITLE
NodeMCU-PyFlasher-Catalina.dmg 5.0.0- how to download  at 0x010000 for ESP32

### ISSUE THREAD

**Issue by Mrszcup** [marcelstoer/nodemcu-pyflasher#87]
default   at 0x000000，This makes ESP32 unable to run

**Comment by marcelstoer** [comment]
It supports "aggregated" binaries that also contain bootloader and partition table for flashing at address 0x000000. See e.g. https://github.com/marcelstoer/nodemcu-custom-build/blob/master/ESP32/script.sh#L21 for an example how to create such files.

**Comment by Mrszcup** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
