### ISSUE TITLE
Nodemcu pyflasher won't start up

### ISSUE THREAD

**Issue by canedje** [marcelstoer/nodemcu-pyflasher#89]
On my PC NodeMCU-PyFlasher.exe is not starting/ running anymore.
It gives short a buzy wheel/sign at the screen at start up but nothing happening. No screen appears, nothing.
I tried also a starup as administrator, the same results
I run latest version.
It did run in the past without any problem.

At my Laptop it is still running fine.

What can be the reason not starting anymore?
Thanks

**Comment by marcelstoer** [comment]
Duplicate of #78
