### ISSUE TITLE
ESP32-S3 NodeMCU PyFlasher stuck at detecting chip type

### ISSUE THREAD

**Issue by OSiRiSNA** [marcelstoer/nodemcu-pyflasher#99]
Hi,

Im trying to flash a .bin file to the TinyS3 and select the COM port it is on and set the chip to Download Mode. It gets to "detecting chip type" and does not progress.

If I set the path to auto-detect then I get "could not open port 'COM8': PermissionError(13, 'Access is denied.', None, 5)".

Any idea what Im doing wrong?

**Comment by Serial-Comma** [comment]
what worked for me was copying the command and running it with sudo in the terminal, at least on linux

**Comment by marcelstoer** [comment]
See #100
